name: Node.js Package
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: cat ~/.npmrc; npm who
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}